config/routes.rb
Rails.application.routes.draw do

  root to: 'home_unauthenticated#index'

  devise_for :users, :skip => [:sessions, :registrations]

  as :user do
    get 'login' => 'devise/sessions#new'
    post 'login' => 'devise/sessions#create', as: :create_session
    get 'logout' => 'devise/sessions#destroy'
    get '/signup' => 'devise/registrations#new'
    post '/signup' => 'devise/registrations#create', as: :create_user
    get 'cancel'   => 'devise/registrations#cancel', as: :cancel_user
    get 'settings' => 'devise/registrations#edit'
    put 'settings' => 'devise/registrations#update', as: :update_user

  end

  resources :register_searches, only: [:index]
  resources :documents, only: [:create]
end

app/models/document.rb
class Document < ActiveRecord::Base
  # change to article
  belongs_to :register_search, inverse_of: :documents
end

app/models/register_search.rb
class RegisterSearch < ActiveRecord::Base
  # change to rquery
  has_many :documents, inverse_of: :register_search, dependent: :destroy
  belongs_to :user, inverse_of: :register_searches
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable
  has_many :register_searches, inverse_of: :user, dependent: :destroy

  validates_uniqueness_of :email, case_sensitive: false, allow_blank: true, if: :email_changed?
  validates_format_of :email, with: Devise.email_regexp, allow_blank: true, if: :email_changed?
  validates_presence_of :password, on: :create
  validates_confirmation_of :password, on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # before_action :authenticate_user

  def authenticate_user
    redirect_to login_url unless user_signed_in?
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  # before_action :authenticate_user

  # POST /documents
  # POST /documents.json
  def create
    term = register_search_params[:term]
    if (query = RegisterSearch.find_by(term: term)) && query.present?
      @documents = query.documents
      # render json: documents, status: 200
    else
      @query = RegisterSearch.create(term: term)
      results = get_articles(@query.term).results
      @documents = build_docs(results)
      # render json: documents, status: 201
    end
  end

  # GET /documents
  # GET /documents.json
  # def index
  #   @documents = Document.all
  # end

  # GET /documents/1
  # GET /documents/1.json
  # def show
  # end

  # GET /documents/new
  # def new
  #   @document = Document.new
  # end

  # GET /documents/1/edit
  # def edit
  # end


  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  # def update
  #   respond_to do |format|
  #     if @document.update(document_params)
  #       format.html { redirect_to @document, notice: 'Document was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @document }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @document.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /documents/1
  # DELETE /documents/1.json
  # def destroy
  #   @document.destroy
  #   respond_to do |format|
  #     format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    def get_articles(term)
      FederalRegister::Article.search(:conditions => {:term => term})
    end

    def build_docs(results)
      documents = Array.new
      results.each do |result|
        document = @query.documents.new({
          document_number: result.document_number,
          html_url:        result.html_url,
          document_type:   result.type,
          title:           result.title
        })
        document.save
        documents << document
      end
      documents
    end

    # Use callbacks to share common setup or constraints between actions.
    # def set_document
    #   @document = Document.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    # def document_params
    #   params.require[:document]
    # end

    def register_search_params
      params.require(:register_search)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # before_action :authenticate_user

  def index
    if current_user
      # get_queries
    end
  end
end

app/controllers/home_unauthenticated_controller.rb
class HomeUnauthenticatedController < ApplicationController

  def index
    @search = RegisterSearch.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :authenticate_user
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/register_searches_helper.rb
module RegisterSearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/documents/_document.html.erb
<div class="document-container <%= cycle('odd', 'even') %>">
  <h3><%= link_to document.title, document.html_url %></h3>
  <h4>Article Type: <%= document.document_type %> </h4>
  <h4>Article Number: <%= document.document_number %> </h4>
  <h4>Excerpts: <%= document.excerpts %> </h4>
  <h4>Article Url: <%= link_to document.html_url, document.html_url %></h4>
</div>

app/views/documents/create.js.erb
var el = $('.naics-results .content');
var html = "<%=j render partial: 'document', collection: @documents %>";

$('.naics-results .loader').removeClass('visible');
el.append(html);

app/views/documents/index.html.erb
<h1>Returned Federal Register Documents</h1>
<hr>
<% if @documents.any? %>
  <%= render partial: 'document', collection: @documents %>
<% else %>
  Your query returned no Documents
<% end %>

app/views/home/index.html.erb
Authenticated user

app/views/home_unauthenticated/index.html.erb
<div class="home unauthorized">
  <div class="row title">
    <div class="col-lg-10 col-lg-offset-1">
      <h1>
        Search the Federal Register for legislation and announcements that affect you.
      </h1>
      <h3><%= link_to("Create an account", signup_url) %> to save and track your federal register articles</h3>
    </div>
  </div>

  <div class="row naics-search">
    <div class="col-lg-4 col-lg-offset-4">
      <%= form_for @search, url: 'documents', remote: true do |f| %>
        <div class="row">
          <div class="col-lg-12">
            <div class="input-group">

              <%= f.text_field(:term, class: 'form-control') %>
              <span class="input-group-btn">
                <%= f.submit("Go!", class: "btn btn-default js-search") %>
              </span>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row naics-results">
    <div class="col-lg-10 col-lg-offset-1">
      <%= image_tag("loading.gif", class: "loader") %>
      <div class="content"></div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="navbar-wrapper">
  <div class="navbar navbar-static-top">
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-left header">
        <%= link_to "Brand Name", root_url, class: "navbar-brand" %>
      </ul>
      <ul class="nav navbar-nav navbar-right padded-right">
        <li><a href="http://www.naics.com/naics-search-results/">Find NAICS codes</a></li>
        <li><a href="#about">About</a></li>
        <li><a href="#contact">Contact</a></li>
        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %><b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Account Settings", settings_url %></li>
              <li class="divider"></li>
              <li><%= link_to "Logout", logout_url %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", login_url %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div><!-- /navbar wrapper -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FlamingGong</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <div class="main">
    <%= yield %>
  </div>

</body>
</html>

app/views/register_searches/_form.html.erb
# <%= form_for(@register_search) do |f| %>
#   <% if @register_search.errors.any? %>
#     <div id="error_explanation">
#       <h2><%= pluralize(@register_search.errors.count, "error") %> prohibited this register_search from being saved:</h2>

#       <ul>
#       <% @register_search.errors.full_messages.each do |message| %>
#         <li><%= message %></li>
#       <% end %>
#       </ul>
#     </div>
#   <% end %>

#   <div class="actions">
#     <%= f.submit %>
#   </div>
# <% end %>

app/views/register_searches/new.html.erb
<form class="search-type">
  <input type="radio" name="search-option" value="text" class="text"checked> Text Search
  <br>
  <input type="radio" name="search-option" value="code" class="code">Search By NAICS code
</form>

<div class="search-options">
  <div class="text-search js-search-option">
    <%= form_tag('/documents', method: :post ) do  %>
      <%= text_field_tag :register_search %>
      <div class="actions">
        <%= submit_tag %>
      </div>
    <% end %>
  </div>
  <div class="code-search js-search-option">
    <%= form_tag('/documents', method: :post) do  %>
      <%= select_tag :register_search, options_for_select(@codes.collect{ |code, name| ["#{code}  :  #{name}", code] }) %>
      <%= submit_tag value = "Submit Search"%>
    <% end %>
  </div>
</div>